log_format demo_main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    'rt=$request_time urt=$upstream_response_time '
                    'ua="$upstream_addr" ref="$http_referer" '
                    'agent="$http_user_agent" request_id="$request_id"';

server {
    listen 8080;
    server_name _;
    resolver 127.0.0.11 ipv6=off valid=10s;

    access_log /var/log/demo/gateway_access.log demo_main;
    error_log /var/log/demo/gateway_error.log warn;

    location /healthz {
        access_log off;
        return 200 "ok\n";
    }

    location /nginx_status {
        stub_status;
        access_log off;
    }

    location = /orders {
        set $orders_upstream http://toxiproxy:18001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Id $request_id;
        proxy_pass $orders_upstream/query$is_args$args;
    }

    location = /orders/create {
        set $orders_upstream http://toxiproxy:18001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header Content-Type $content_type;
        proxy_pass $orders_upstream/write;
    }

    location = /inventory {
        set $inventory_upstream http://toxiproxy:18002;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Id $request_id;
        proxy_pass $inventory_upstream/query$is_args$args;
    }

    location = /inventory/reserve {
        set $inventory_upstream http://toxiproxy:18002;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header Content-Type $content_type;
        proxy_pass $inventory_upstream/write;
    }

    location = /billing {
        set $billing_upstream http://toxiproxy:18003;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Id $request_id;
        proxy_pass $billing_upstream/query$is_args$args;
    }

    location = /billing/charge {
        set $billing_upstream http://toxiproxy:18003;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header Content-Type $content_type;
        proxy_pass $billing_upstream/write;
    }
}
