global:
  resolve_timeout: 5m

route:
  receiver: aiops-webhook
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 15s
  repeat_interval: 2m

receivers:
  - name: aiops-webhook
    webhook_configs:
      - url: http://web:8000/genai/alerts/ingest/
        send_resolved: true
