# Generated by Django 5.2.6 on 2025-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genaichathistory',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
