# Generated by Django 4.2.16 on 2026-04-20 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genai', '0008_investigationrun_toolinvocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBehaviorVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('name', models.CharField(default='default', max_length=120)),
                ('prompt_version', models.CharField(default='prompt-v1', max_length=120)),
                ('policy_version', models.CharField(default='policy-v1', max_length=120)),
                ('model_version', models.CharField(default='model-v1', max_length=120)),
                ('evidence_rules_version', models.CharField(default='evidence-v1', max_length=120)),
                ('ranking_version', models.CharField(default='ranking-v1', max_length=120)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('execution_type', models.CharField(default='diagnostic', max_length=32)),
                ('action_type', models.CharField(blank=True, default='', max_length=64)),
                ('service', models.CharField(blank=True, default='', max_length=120)),
                ('environment', models.CharField(blank=True, default='', max_length=64)),
                ('target_host', models.CharField(blank=True, default='', max_length=255)),
                ('command', models.TextField(blank=True, default='')),
                ('action_json', models.JSONField(blank=True, default=dict)),
                ('action_signature', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('request_signature', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('approval_expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('rollback_json', models.JSONField(blank=True, default=dict)),
                ('policy_decision_json', models.JSONField(blank=True, default=dict)),
                ('ranking_json', models.JSONField(blank=True, default=dict)),
                ('verification_json', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('context_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approval_required', 'Approval Required'), ('approved', 'Approved'), ('dry_run', 'Dry Run'), ('blocked', 'Blocked'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='planned', max_length=32)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_execution_intents', to=settings.AUTH_USER_MODEL)),
                ('behavior_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_intents', to='genai.agentbehaviorversion')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_intents', to='genai.incident')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_intents', to='genai.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_execution_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplayScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('source', models.CharField(default='execution', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('alert_payload_json', models.JSONField(blank=True, default=dict)),
                ('metrics_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('logs_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('traces_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('dependency_context_json', models.JSONField(blank=True, default=dict)),
                ('prior_incident_memory_json', models.JSONField(blank=True, default=dict)),
                ('chosen_action_json', models.JSONField(blank=True, default=dict)),
                ('outcome_json', models.JSONField(blank=True, default=dict)),
                ('behavior_version_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_scenarios', to='genai.incident')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_scenarios', to='genai.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplayEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=32)),
                ('scores_json', models.JSONField(blank=True, default=dict)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_evaluations', to='genai.executionintent')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='genai.replayscenario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemediationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('action_type', models.CharField(blank=True, default='', max_length=64)),
                ('service', models.CharField(blank=True, default='', max_length=120)),
                ('environment', models.CharField(blank=True, default='', max_length=64)),
                ('context_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('action_signature', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('success', models.BooleanField(default=False)),
                ('verification_status', models.CharField(blank=True, default='', max_length=64)),
                ('time_to_recovery_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_within_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('blast_radius_risk', models.FloatField(blank=True, null=True)),
                ('operator_override', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='genai.executionintent')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_outcomes', to='genai.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
