# Generated by Django 4.2.16 on 2026-04-20 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genai', '0009_agentbehaviorversion_executionintent_replayscenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('feedback_type', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('manual_fix', 'Manual Fix Applied')], max_length=32)),
                ('outcome_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('partial', 'Partial'), ('poor', 'Poor'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('service', models.CharField(blank=True, default='', max_length=120)),
                ('environment', models.CharField(blank=True, default='', max_length=64)),
                ('action_type', models.CharField(blank=True, default='', max_length=64)),
                ('context_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('original_action_json', models.JSONField(blank=True, default=dict)),
                ('submitted_action_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_feedback', to='genai.executionintent')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_feedback', to='genai.incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_operator_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
