# Generated by Django 4.2.16 on 2026-05-04 05:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0010_operatorfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('local_path', models.CharField(max_length=1024, unique=True)),
                ('default_branch', models.CharField(blank=True, default='main', max_length=255)),
                ('provider', models.CharField(blank=True, default='local', max_length=64)),
                ('repo_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('last_index_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SymbolRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('source_symbol', models.CharField(db_index=True, max_length=255)),
                ('source_file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('target_symbol', models.CharField(db_index=True, max_length=255)),
                ('target_file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('relation_type', models.CharField(default='calls', max_length=64)),
                ('confidence', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_relations', to='genai.repositoryindex')),
            ],
            options={
                'ordering': ['source_symbol', 'target_symbol'],
                'unique_together': {('repository_index', 'source_symbol', 'source_file_path', 'target_symbol', 'target_file_path', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='SpanBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('service_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('span_name', models.CharField(db_index=True, max_length=255)),
                ('symbol_name', models.CharField(blank=True, default='', max_length=255)),
                ('symbol_file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('line_start', models.PositiveIntegerField(blank=True, null=True)),
                ('line_end', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='span_bindings', to='genai.repositoryindex')),
            ],
            options={
                'ordering': ['span_name'],
                'unique_together': {('repository_index', 'span_name', 'symbol_name', 'symbol_file_path')},
            },
        ),
        migrations.CreateModel(
            name='ServiceRepositoryBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('service_name', models.CharField(db_index=True, max_length=120)),
                ('application_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('team_name', models.CharField(blank=True, default='', max_length=255)),
                ('ownership_confidence', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bindings', to='genai.repositoryindex')),
            ],
            options={
                'ordering': ['service_name', 'application_name'],
                'unique_together': {('service_name', 'application_name', 'repository_index')},
            },
        ),
        migrations.CreateModel(
            name='RouteBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('service_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('http_method', models.CharField(blank=True, default='ANY', max_length=16)),
                ('route_pattern', models.CharField(db_index=True, max_length=512)),
                ('handler_name', models.CharField(blank=True, default='', max_length=255)),
                ('handler_file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('line_start', models.PositiveIntegerField(blank=True, null=True)),
                ('line_end', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_bindings', to='genai.repositoryindex')),
            ],
            options={
                'ordering': ['route_pattern', 'http_method'],
                'unique_together': {('repository_index', 'http_method', 'route_pattern', 'handler_name', 'handler_file_path')},
            },
        ),
        migrations.CreateModel(
            name='DeploymentBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('service_name', models.CharField(db_index=True, max_length=120)),
                ('environment', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('version', models.CharField(db_index=True, max_length=255)),
                ('commit_sha', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_bindings', to='genai.repositoryindex')),
            ],
            options={
                'ordering': ['-deployed_at', '-created_at'],
                'unique_together': {('service_name', 'environment', 'version', 'repository_index')},
            },
        ),
        migrations.CreateModel(
            name='CodeChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('commit_sha', models.CharField(db_index=True, max_length=64)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('changed_files', models.JSONField(blank=True, default=list)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_records', to='genai.repositoryindex')),
            ],
            options={
                'ordering': ['-committed_at', '-created_at'],
                'unique_together': {('repository_index', 'commit_sha')},
            },
        ),
    ]
