# Generated by Django 4.2.16 on 2026-05-05 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0012_alter_targetonboardingrequest_pem_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPolicyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('target_type', models.CharField(choices=[('linux', 'Linux'), ('kubernetes', 'Kubernetes')], default='linux', max_length=32)),
                ('runtime_type', models.CharField(choices=[('any', 'Any'), ('systemd', 'Systemd'), ('docker', 'Docker'), ('standalone', 'Standalone'), ('kubernetes', 'Kubernetes')], default='any', max_length=32)),
                ('allow_service_status', models.BooleanField(default=True)),
                ('allow_service_restart', models.BooleanField(default=False)),
                ('allow_docker_logs', models.BooleanField(default=False)),
                ('allow_docker_restart', models.BooleanField(default=False)),
                ('allow_journal_logs', models.BooleanField(default=True)),
                ('allow_file_logs', models.BooleanField(default=False)),
                ('allow_db_diagnostics', models.BooleanField(default=False)),
                ('allow_db_changes', models.BooleanField(default=False)),
                ('allow_process_kill', models.BooleanField(default=False)),
                ('requires_approval_for_restart', models.BooleanField(default=True)),
                ('requires_approval_for_write_actions', models.BooleanField(default=True)),
                ('sudo_mode', models.CharField(choices=[('none', 'None'), ('limited', 'Limited'), ('full', 'Full')], default='limited', max_length=16)),
                ('allowed_command_patterns', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetServiceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('service_name', models.CharField(db_index=True, max_length=160)),
                ('service_kind', models.CharField(choices=[('systemd', 'Systemd'), ('docker_container', 'Docker Container'), ('process', 'Process'), ('database', 'Database'), ('kubernetes_workload', 'Kubernetes Workload')], max_length=32)),
                ('systemd_unit', models.CharField(blank=True, default='', max_length=255)),
                ('container_name', models.CharField(blank=True, default='', max_length=255)),
                ('process_name', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('restart_command_template', models.TextField(blank=True, default='')),
                ('status_command_template', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bindings', to='genai.target')),
            ],
            options={
                'ordering': ['service_name'],
                'unique_together': {('target', 'service_name', 'service_kind', 'systemd_unit', 'container_name', 'process_name')},
            },
        ),
        migrations.CreateModel(
            name='TargetRuntimeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('app', 'Application'), ('db', 'Database'), ('cache', 'Cache'), ('gateway', 'Gateway'), ('custom', 'Custom')], default='app', max_length=32)),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('staging', 'Staging'), ('dev', 'Development'), ('test', 'Test')], default='prod', max_length=32)),
                ('runtime_type', models.CharField(choices=[('systemd', 'Systemd'), ('docker', 'Docker'), ('standalone', 'Standalone'), ('kubernetes', 'Kubernetes'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('os_family', models.CharField(blank=True, default='', max_length=64)),
                ('docker_available', models.BooleanField(default=False)),
                ('systemd_available', models.BooleanField(default=False)),
                ('primary_restart_mode', models.CharField(choices=[('systemctl', 'Systemctl'), ('docker', 'Docker'), ('kubectl', 'Kubectl'), ('process', 'Process'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_profile', to='genai.target')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetPolicyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('override_json', models.JSONField(blank=True, default=dict)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_apply_status', models.CharField(blank=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_assignments', to='genai.targetpolicyprofile')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_assignment', to='genai.target')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('source_type', models.CharField(choices=[('journald', 'Journald'), ('file', 'File'), ('docker', 'Docker'), ('database', 'Database'), ('kubernetes', 'Kubernetes')], max_length=32)),
                ('journal_unit', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('container_name', models.CharField(blank=True, default='', max_length=255)),
                ('stream_family', models.CharField(blank=True, default='', max_length=120)),
                ('parser_name', models.CharField(blank=True, default='', max_length=120)),
                ('include_patterns', models.JSONField(blank=True, default=list)),
                ('exclude_patterns', models.JSONField(blank=True, default=list)),
                ('shipper_type', models.CharField(blank=True, default='', max_length=64)),
                ('parser_type', models.CharField(blank=True, default='', max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_sources', to='genai.targetservicebinding')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='genai.target')),
            ],
            options={
                'ordering': ['target', '-is_primary', 'source_type'],
            },
        ),
        migrations.CreateModel(
            name='TargetLogIngestionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('shipper_type', models.CharField(default='fluent-bit', max_length=64)),
                ('stream_family', models.CharField(blank=True, default='', max_length=120)),
                ('opensearch_pipeline', models.CharField(blank=True, default='', max_length=255)),
                ('record_metadata_json', models.JSONField(blank=True, default=dict)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_apply_status', models.CharField(blank=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_ingestion_profile', to='genai.target')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
