# Generated by Django 4.2.16 on 2026-05-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0013_targetpolicyprofile_targetservicebinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetonboardingrequest',
            name='config_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='targetonboardingrequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='targetonboardingrequest',
            name='policy_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_requests', to='genai.targetpolicyprofile'),
        ),
        migrations.AddField(
            model_name='targetonboardingrequest',
            name='runtime_type',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='targetonboardingrequest',
            name='target_environment',
            field=models.CharField(default='prod', max_length=32),
        ),
        migrations.AddField(
            model_name='targetonboardingrequest',
            name='target_role',
            field=models.CharField(default='app', max_length=32),
        ),
    ]
