# Generated by Django 4.2.16 on 2026-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0014_targetonboardingrequest_config_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationrun',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='contradicting_evidence_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='current_stage',
            field=models.CharField(blank=True, default='queued', max_length=64),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='evidence_bundle_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='hypotheses_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='missing_evidence_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='planner_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='workflow_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='investigationrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('scoping', 'Scoping'), ('collecting_evidence', 'Collecting Evidence'), ('assessing_evidence', 'Assessing Evidence'), ('planning_next_step', 'Planning Next Step'), ('awaiting_approval', 'Awaiting Approval'), ('executing', 'Executing'), ('verifying', 'Verifying'), ('resolved', 'Resolved'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=32),
        ),
    ]
