# Generated by Django 4.2.16 on 2026-05-06 04:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0015_investigationrun_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('data_category', models.CharField(choices=[('hot_telemetry', 'Hot Telemetry'), ('operational_state', 'Operational State'), ('runtime_knowledge', 'Runtime Knowledge'), ('evidence_memory', 'Evidence Memory'), ('learning_memory', 'Learning Memory'), ('archived_artifact', 'Archived Artifact')], max_length=32)),
                ('primary_store', models.CharField(choices=[('postgres', 'Postgres'), ('redis', 'Redis'), ('opensearch', 'OpenSearch'), ('victoriametrics', 'VictoriaMetrics'), ('tempo', 'Tempo'), ('object_storage', 'Object Storage'), ('vector_backend', 'Vector Backend')], max_length=32)),
                ('archive_store', models.CharField(blank=True, choices=[('postgres', 'Postgres'), ('redis', 'Redis'), ('opensearch', 'OpenSearch'), ('victoriametrics', 'VictoriaMetrics'), ('tempo', 'Tempo'), ('object_storage', 'Object Storage'), ('vector_backend', 'Vector Backend')], default='', max_length=32)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('archive_after_days', models.PositiveIntegerField(default=0)),
                ('purge_after_days', models.PositiveIntegerField(default=0)),
                ('hold_supported', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('policy_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['data_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('data_category', models.CharField(choices=[('hot_telemetry', 'Hot Telemetry'), ('operational_state', 'Operational State'), ('runtime_knowledge', 'Runtime Knowledge'), ('evidence_memory', 'Evidence Memory'), ('learning_memory', 'Learning Memory'), ('archived_artifact', 'Archived Artifact')], default='evidence_memory', max_length=32)),
                ('primary_store', models.CharField(choices=[('postgres', 'Postgres'), ('redis', 'Redis'), ('opensearch', 'OpenSearch'), ('victoriametrics', 'VictoriaMetrics'), ('tempo', 'Tempo'), ('object_storage', 'Object Storage'), ('vector_backend', 'Vector Backend')], default='postgres', max_length=32)),
                ('archive_store', models.CharField(blank=True, choices=[('postgres', 'Postgres'), ('redis', 'Redis'), ('opensearch', 'OpenSearch'), ('victoriametrics', 'VictoriaMetrics'), ('tempo', 'Tempo'), ('object_storage', 'Object Storage'), ('vector_backend', 'Vector Backend')], default='object_storage', max_length=32)),
                ('lifecycle_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('pruned', 'Pruned')], default='active', max_length=16)),
                ('evidence_summary_json', models.JSONField(blank=True, default=dict)),
                ('artifact_references_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_bundles', to='genai.incident')),
                ('investigation_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_bundle_record', to='genai.investigationrun')),
                ('retention_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_bundles', to='genai.dataretentionpolicy')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('sequence_index', models.PositiveIntegerField(default=0)),
                ('entry_type', models.CharField(choices=[('stage_transition', 'Stage Transition'), ('planner', 'Planner'), ('evidence_assessment', 'Evidence Assessment'), ('verification', 'Verification'), ('summary', 'Summary')], default='stage_transition', max_length=32)),
                ('stage', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entries', to='genai.evidencebundle')),
                ('investigation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entries', to='genai.investigationrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('stage', models.CharField(blank=True, default='', max_length=64)),
                ('iteration_index', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('planner_json', models.JSONField(blank=True, default=dict)),
                ('evidence_bundle_json', models.JSONField(blank=True, default=dict)),
                ('missing_evidence_json', models.JSONField(blank=True, default=list)),
                ('contradicting_evidence_json', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='genai.evidencebundle')),
                ('investigation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_snapshots', to='genai.investigationrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='investigationtranscript',
            constraint=models.UniqueConstraint(fields=('investigation_run', 'sequence_index'), name='uniq_investigation_transcript_sequence'),
        ),
    ]
