# Generated by Django 4.2.16 on 2026-05-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0016_dataretentionpolicy_evidencebundle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataretentionpolicy',
            options={'ordering': ['data_category', 'subject_type', 'deployment_mode', 'name']},
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='deployment_mode',
            field=models.CharField(choices=[('any', 'Any'), ('docker_single_node', 'Docker Single Node'), ('kubernetes_standard', 'Kubernetes Standard'), ('kubernetes_enterprise', 'Kubernetes Enterprise')], default='any', max_length=32),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='object_storage_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='storage_defaults_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='subject_type',
            field=models.CharField(choices=[('logs', 'Logs'), ('traces', 'Traces'), ('metrics', 'Metrics'), ('investigation_evidence', 'Investigation Evidence'), ('execution_history', 'Execution History'), ('learning_artifacts', 'Learning Artifacts'), ('runtime_inventory', 'Runtime Inventory')], default='investigation_evidence', max_length=40),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='trace_backend',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='vector_store_required',
            field=models.BooleanField(default=False),
        ),
    ]
