# Generated by Django 4.2.16 on 2026-05-07 06:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0018_lifecycle_archive_track3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('integration_type', models.CharField(choices=[('prometheus', 'Prometheus'), ('victoriametrics', 'VictoriaMetrics'), ('tempo', 'Tempo'), ('jaeger', 'Jaeger'), ('opensearch', 'OpenSearch'), ('elasticsearch', 'Elasticsearch'), ('loki', 'Loki'), ('splunk', 'Splunk'), ('dynatrace', 'Dynatrace'), ('datadog', 'Datadog'), ('newrelic', 'New Relic'), ('nagios', 'Nagios'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('custom', 'Custom')], max_length=64)),
                ('category', models.CharField(choices=[('metrics', 'Metrics'), ('logs', 'Logs'), ('traces', 'Traces'), ('alerts', 'Alerts'), ('topology', 'Topology/Inventory'), ('cloud', 'Cloud Control Plane'), ('mixed', 'Mixed/Hybrid')], max_length=64)),
                ('endpoint_url', models.CharField(blank=True, default='', max_length=1024)),
                ('auth_mode', models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('iam_role', 'IAM Role')], default='none', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failing', 'Failing'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failing', 'Failing')], max_length=32)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='genai.integration')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('secret_ref', models.CharField(blank=True, default='', help_text='Reference to external secret manager or encrypted store', max_length=255)),
                ('credential_metadata', models.JSONField(blank=True, default=dict)),
                ('rotation_status', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='genai.integration')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('environment', models.CharField(blank=True, default='', max_length=120)),
                ('application_name', models.CharField(blank=True, default='', max_length=120)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number means higher priority for query resolution')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='genai.integration')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_bindings', to='genai.target')),
            ],
            options={
                'ordering': ['priority', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudAccountBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('provider', models.CharField(default='aws', max_length=64)),
                ('account_id', models.CharField(blank=True, default='', max_length=120)),
                ('subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('project_id', models.CharField(blank=True, default='', max_length=120)),
                ('scope_name', models.CharField(blank=True, default='', max_length=255)),
                ('environment', models.CharField(blank=True, default='', max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_bindings', to='genai.integration')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
