# Generated by Django 4.2.16 on 2026-05-13 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0021_incident_number_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppression_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('alert_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('service_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('target_host', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('environment', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='suppression_rule', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('service_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('target_host', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('environment', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, default='maintenance_window', max_length=255)),
                ('created_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentCorrelationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_correlation_links', to='genai.incident')),
                ('source_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_correlation_links', to='genai.incident')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('source_incident', 'related_incident')},
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('source', models.CharField(db_index=True, default='unknown', max_length=64)),
                ('lifecycle_key', models.CharField(db_index=True, max_length=255)),
                ('alert_name', models.CharField(db_index=True, max_length=255)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved'), ('unknown', 'Unknown')], db_index=True, default='firing', max_length=32)),
                ('severity', models.CharField(blank=True, db_index=True, default='warning', max_length=32)),
                ('service_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('target_host', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('environment', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('namespace', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('cluster', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('repeat_count', models.PositiveIntegerField(default=1)),
                ('suppressed', models.BooleanField(db_index=True, default=False)),
                ('suppression_reason', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='genai.incident')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'unique_together': {('source', 'lifecycle_key')},
            },
        ),
    ]
