# Generated by Django 4.2.16 on 2026-05-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0022_alertsuppression_maintenancewindow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='auth_mode',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('iam_role', 'IAM Role'), ('webhook', 'Webhook URL')], default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='integration',
            name='category',
            field=models.CharField(choices=[('metrics', 'Metrics'), ('logs', 'Logs'), ('traces', 'Traces'), ('alerts', 'Alerts'), ('topology', 'Topology/Inventory'), ('cloud', 'Cloud Control Plane'), ('itsm', 'ITSM/Incident Management'), ('notifications', 'Notifications'), ('deployments', 'Deployments'), ('code', 'Source Control'), ('mixed', 'Mixed/Hybrid')], max_length=64),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('prometheus', 'Prometheus'), ('victoriametrics', 'VictoriaMetrics'), ('tempo', 'Tempo'), ('jaeger', 'Jaeger'), ('opensearch', 'OpenSearch'), ('elasticsearch', 'Elasticsearch'), ('loki', 'Loki'), ('splunk', 'Splunk'), ('dynatrace', 'Dynatrace'), ('datadog', 'Datadog'), ('newrelic', 'New Relic'), ('nagios', 'Nagios'), ('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP'), ('alertmanager', 'Alertmanager'), ('pagerduty', 'PagerDuty'), ('servicenow', 'ServiceNow'), ('jira', 'Jira'), ('opsgenie', 'Opsgenie'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('jenkins', 'Jenkins'), ('argocd', 'Argo CD'), ('fluxcd', 'Flux CD'), ('kubernetes', 'Kubernetes'), ('custom', 'Custom')], max_length=64),
        ),
    ]
