# Generated by Django 4.2.16 on 2026-05-14 04:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0023_alter_integration_auth_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentExternalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('external_key', models.CharField(blank=True, default='', max_length=255)),
                ('external_url', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('created', 'Created'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='created', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tickets', to='genai.incident')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_tickets', to='genai.integration')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('incident', 'integration')},
            },
        ),
    ]
