# Generated by Django 4.2.16 on 2026-05-14 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_default_tenant_and_backfill(apps, schema_editor):
    Tenant = apps.get_model("genai", "Tenant")
    TenantMembership = apps.get_model("genai", "TenantMembership")
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    tenant, _ = Tenant.objects.get_or_create(
        slug="default-workspace",
        defaults={
            "name": "Default Workspace",
            "domain": "",
            "metadata_json": {"created_by_migration": "0025"},
        },
    )

    for user in User.objects.all():
        role = "owner" if user.is_superuser else "admin"
        TenantMembership.objects.get_or_create(
            tenant=tenant,
            user=user,
            defaults={"role": role, "is_active": True},
        )

    direct_models = [
        "AlertEvent",
        "AlertSuppression",
        "ChatSession",
        "EnrollmentToken",
        "EvidenceBundle",
        "ExecutionIntent",
        "Incident",
        "IncidentCorrelationLink",
        "IncidentExternalTicket",
        "Integration",
        "InvestigationRun",
        "MaintenanceWindow",
        "OperatorFeedback",
        "RemediationOutcome",
        "ReplayScenario",
        "RepositoryIndex",
        "Runbook",
        "Target",
        "TargetOnboardingRequest",
        "ToolInvocation",
    ]
    for model_name in direct_models:
        model = apps.get_model("genai", model_name)
        model.objects.filter(tenant__isnull=True).update(tenant=tenant)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genai', '0024_incidentexternalticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('domain', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operator'), ('responder', 'Responder'), ('viewer', 'Viewer'), ('auditor', 'Auditor')], default='viewer', max_length=32)),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_tenant_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_tenant_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='genai.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('object_type', models.CharField(blank=True, default='', max_length=120)),
                ('object_id', models.CharField(blank=True, default='', max_length=120)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_tenant_audit_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='genai.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alertevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='alertsuppression',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_suppressions', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='enrollmenttoken',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_tokens', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='evidencebundle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_bundles', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='executionintent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_intents', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='incident',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='incidentcorrelationlink',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_correlation_links', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='incidentexternalticket',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_external_tickets', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='integration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_runs', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='maintenancewindow',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='operatorfeedback',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_feedback', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='remediationoutcome',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_outcomes', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='replayscenario',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_scenarios', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='repositoryindex',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_indexes', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='runbook',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runbooks', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='target',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='targetonboardingrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_requests', to='genai.tenant'),
        ),
        migrations.AddField(
            model_name='toolinvocation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_invocations', to='genai.tenant'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operator'), ('responder', 'Responder'), ('viewer', 'Viewer'), ('auditor', 'Auditor')], default='viewer', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_tenant_memberships_invited', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='genai.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiops_tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant__name', 'user__username'],
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.RunPython(create_default_tenant_and_backfill, noop_reverse),
    ]
