# Generated by Django 4.2.16 on 2026-05-14 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0025_tenant_tenantinvitation_tenantauditevent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alertevent',
            unique_together={('tenant', 'source', 'lifecycle_key')},
        ),
    ]
