# Generated by Django 4.2.16 on 2026-05-14 09:39

from django.db import migrations, models
import django.db.models.deletion
import genai.models


TENANT_OWNED_MODELS = [
    'AlertEvent',
    'AlertSuppression',
    'ChatSession',
    'EnrollmentToken',
    'EvidenceBundle',
    'ExecutionIntent',
    'Incident',
    'IncidentCorrelationLink',
    'IncidentExternalTicket',
    'Integration',
    'InvestigationRun',
    'MaintenanceWindow',
    'OperatorFeedback',
    'RemediationOutcome',
    'ReplayScenario',
    'RepositoryIndex',
    'Runbook',
    'Target',
    'TargetOnboardingRequest',
    'ToolInvocation',
]


def backfill_default_tenant(apps, schema_editor):
    Tenant = apps.get_model('genai', 'Tenant')
    tenant, _ = Tenant.objects.get_or_create(
        slug='default-workspace',
        defaults={'name': 'Default Workspace', 'metadata_json': {'created_by': 'tenant_backfill'}},
    )
    for model_name in TENANT_OWNED_MODELS:
        model = apps.get_model('genai', model_name)
        model.objects.filter(tenant__isnull=True).update(tenant_id=tenant.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0028_executionintent_rollback_snapshot'),
    ]

    operations = [
        migrations.RunPython(backfill_default_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='alertevent',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='alertsuppression',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='alert_suppressions', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='enrollmenttoken',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='evidencebundle',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_bundles', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='executionintent',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='execution_intents', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='incidentcorrelationlink',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='incident_correlation_links', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='incidentexternalticket',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='incident_external_tickets', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='investigationrun',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_runs', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='maintenancewindow',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='operatorfeedback',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='operator_feedback', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='remediationoutcome',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='remediation_outcomes', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='replayscenario',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='replay_scenarios', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='repositoryindex',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='repository_indexes', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='runbook',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='runbooks', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='target',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='targetonboardingrequest',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_requests', to='genai.tenant'),
        ),
        migrations.AlterField(
            model_name='toolinvocation',
            name='tenant',
            field=models.ForeignKey(default=genai.models.default_tenant_pk, on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='genai.tenant'),
        ),
    ]
