# Generated by Django 5.2.6 on 2025-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='vector',
            field=models.JSONField(blank=True, default=True, null=True),
        ),
    ]
