# Generated by Django 3.2 on 2025-09-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_search', '0002_alter_documentchunk_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='vector',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
