# Generated by Django 3.2 on 2025-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_search', '0003_alter_documentchunk_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
