from django.core.management.base import BaseCommand

from genai.models import DataRetentionPolicy


RETENTION_POLICY_SEED = [
    {
        "slug": "metrics-docker-default",
        "name": "Metrics Docker Default",
        "data_category": "hot_telemetry",
        "subject_type": "metrics",
        "deployment_mode": "docker_single_node",
        "primary_store": "victoriametrics",
        "archive_store": "object_storage",
        "retention_days": 14,
        "archive_after_days": 7,
        "purge_after_days": 30,
        "hold_supported": False,
        "object_storage_required": False,
        "vector_store_required": False,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {"docker_volume_required": True, "kubernetes_storage_class_required": False},
        "policy_json": {"metrics_backend": "victoriametrics", "trace_backend_direction": "tempo"},
        "notes": "Single-node Docker metrics retention using local VictoriaMetrics storage.",
    },
    {
        "slug": "metrics-kubernetes-default",
        "name": "Metrics Kubernetes Default",
        "data_category": "hot_telemetry",
        "subject_type": "metrics",
        "deployment_mode": "kubernetes_standard",
        "primary_store": "victoriametrics",
        "archive_store": "object_storage",
        "retention_days": 21,
        "archive_after_days": 14,
        "purge_after_days": 45,
        "hold_supported": False,
        "object_storage_required": False,
        "vector_store_required": False,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {"docker_volume_required": False, "kubernetes_storage_class_required": True},
        "policy_json": {"metrics_backend": "victoriametrics"},
        "notes": "Kubernetes standard metrics retention using PVC-backed VictoriaMetrics.",
    },
    {
        "slug": "logs-default",
        "name": "Logs Default",
        "data_category": "hot_telemetry",
        "subject_type": "logs",
        "deployment_mode": "any",
        "primary_store": "opensearch",
        "archive_store": "object_storage",
        "retention_days": 14,
        "archive_after_days": 7,
        "purge_after_days": 30,
        "hold_supported": True,
        "object_storage_required": True,
        "vector_store_required": False,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {
            "docker_volume_required": True,
            "kubernetes_storage_class_required": True,
            "opensearch_stream_families": ["logs-linux-default", "logs-docker-default", "logs-kubernetes-default"],
        },
        "policy_json": {"log_backend": "opensearch", "shipper": "fluent-bit"},
        "notes": "Centralized logs remain searchable in OpenSearch and require archive-capable object storage for longer retention.",
    },
    {
        "slug": "traces-default",
        "name": "Traces Default",
        "data_category": "hot_telemetry",
        "subject_type": "traces",
        "deployment_mode": "any",
        "primary_store": "tempo",
        "archive_store": "object_storage",
        "retention_days": 14,
        "archive_after_days": 7,
        "purge_after_days": 45,
        "hold_supported": True,
        "object_storage_required": True,
        "vector_store_required": False,
        "trace_backend": "tempo",
        "is_default": True,
        "storage_defaults_json": {"tempo_object_storage_required": True},
        "policy_json": {"trace_backend": "tempo", "jaeger_transition_supported": True},
        "notes": "Long-term trace direction is Tempo with object storage for durable retention.",
    },
    {
        "slug": "operational-state-default",
        "name": "Operational State Default",
        "data_category": "operational_state",
        "subject_type": "runtime_inventory",
        "deployment_mode": "any",
        "primary_store": "postgres",
        "archive_store": "",
        "retention_days": 365,
        "archive_after_days": 0,
        "purge_after_days": 0,
        "hold_supported": True,
        "object_storage_required": False,
        "vector_store_required": False,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {"postgres_backup_required": True},
        "policy_json": {"system_of_record": "postgres"},
        "notes": "System-of-record operational state should remain durable in Postgres.",
    },
    {
        "slug": "runtime-knowledge-default",
        "name": "Runtime Knowledge Default",
        "data_category": "runtime_knowledge",
        "subject_type": "runtime_inventory",
        "deployment_mode": "any",
        "primary_store": "postgres",
        "archive_store": "object_storage",
        "retention_days": 180,
        "archive_after_days": 90,
        "purge_after_days": 365,
        "hold_supported": True,
        "object_storage_required": True,
        "vector_store_required": False,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {"postgres_backup_required": True, "archive_manifest_required": True},
        "policy_json": {"runtime_profiles": True, "service_bindings": True},
        "notes": "Target runtime knowledge stays in Postgres and can be archived for historical audits.",
    },
    {
        "slug": "evidence-memory-default",
        "name": "Evidence Memory Default",
        "data_category": "evidence_memory",
        "subject_type": "investigation_evidence",
        "deployment_mode": "any",
        "primary_store": "postgres",
        "archive_store": "object_storage",
        "retention_days": 30,
        "archive_after_days": 14,
        "purge_after_days": 120,
        "hold_supported": True,
        "object_storage_required": True,
        "vector_store_required": False,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {"bundle_store": "postgres", "archive_manifest_required": True},
        "policy_json": {"bundle_store": "postgres", "archive_ready": True},
        "notes": "Investigation evidence bundles, transcripts, and snapshots remain queryable before archive.",
    },
    {
        "slug": "execution-history-default",
        "name": "Execution History Default",
        "data_category": "evidence_memory",
        "subject_type": "execution_history",
        "deployment_mode": "any",
        "primary_store": "postgres",
        "archive_store": "object_storage",
        "retention_days": 60,
        "archive_after_days": 30,
        "purge_after_days": 180,
        "hold_supported": True,
        "object_storage_required": True,
        "vector_store_required": False,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {"postgres_backup_required": True},
        "policy_json": {"execution_intents": True, "remediation_outcomes": True},
        "notes": "Execution history should remain queryable for audit and operator review before archive.",
    },
    {
        "slug": "learning-memory-default",
        "name": "Learning Memory Default",
        "data_category": "learning_memory",
        "subject_type": "learning_artifacts",
        "deployment_mode": "any",
        "primary_store": "vector_backend",
        "archive_store": "object_storage",
        "retention_days": 90,
        "archive_after_days": 60,
        "purge_after_days": 365,
        "hold_supported": True,
        "object_storage_required": True,
        "vector_store_required": True,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {"vector_backend": "abstract", "separate_from_postgres": True},
        "policy_json": {"vector_backend": "abstract", "notes": "pgvector early, Weaviate-capable later"},
        "notes": "Derived learning artifacts should sit behind the vector abstraction boundary.",
    },
    {
        "slug": "archived-artifact-default",
        "name": "Archived Artifact Default",
        "data_category": "archived_artifact",
        "subject_type": "investigation_evidence",
        "deployment_mode": "any",
        "primary_store": "object_storage",
        "archive_store": "object_storage",
        "retention_days": 365,
        "archive_after_days": 0,
        "purge_after_days": 1095,
        "hold_supported": True,
        "object_storage_required": True,
        "vector_store_required": False,
        "trace_backend": "",
        "is_default": True,
        "storage_defaults_json": {"object_storage_required": True},
        "policy_json": {"archive_backend": "object_storage"},
        "notes": "Long-term archives and exported evidence packages live in object storage.",
    },
]


class Command(BaseCommand):
    help = "Seed default data retention policies for Track 3 lifecycle management."

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for payload in RETENTION_POLICY_SEED:
            slug = payload["slug"]
            defaults = dict(payload)
            defaults.pop("slug", None)
            policy, was_created = DataRetentionPolicy.objects.update_or_create(
                slug=slug,
                defaults=defaults,
            )
            if was_created:
                created += 1
            else:
                updated += 1
            self.stdout.write(self.style.SUCCESS(f"Seeded retention policy {policy.slug}"))
        self.stdout.write(self.style.SUCCESS(f"Retention policies complete: {created} created, {updated} updated"))
