import json
from typing import Any, Callable, Dict, List


def generate_runbook_payload(
    incident,
    *,
    llm_query: Callable[[str], tuple],
    runbook_model,
    timeline_event_model,
    request_user,
    logger,
) -> Dict[str, Any]:
    timeline_events: List[Dict[str, Any]] = []
    for ev in incident.timeline.all().values("event_type", "title", "detail", "created_at"):
        timeline_events.append({
            "event_type": ev["event_type"],
            "title": ev["title"],
            "detail": ev["detail"],
            "created_at": ev["created_at"].isoformat(),
        })

    prompt = (
        "You are a senior SRE. Given the incident summary and investigation timeline below, "
        "generate a detailed, actionable runbook in Markdown format that a new engineer can follow "
        "to detect, diagnose, and remediate this type of incident in the future.\n\n"
        "Structure the runbook with these exact sections:\n"
        "## Overview\n## Detection\n## Diagnosis Steps\n## Remediation\n## Validation\n## Prevention\n\n"
        f"INCIDENT:\n"
        f"Title: {incident.title}\n"
        f"Severity: {incident.severity} | Priority: {incident.priority}\n"
        f"Service: {incident.primary_service} | Host: {incident.target_host}\n"
        f"Summary: {incident.summary}\n"
        f"Reasoning: {incident.reasoning}\n\n"
        f"TIMELINE ({len(timeline_events)} events):\n"
        + json.dumps(timeline_events, indent=2)[:8000]
    )

    ok, _, text = llm_query(prompt)
    if not ok:
        raise RuntimeError(text)

    title = f"Runbook: {incident.title}"
    runbook = runbook_model.objects.create(incident=incident, title=title, content=text)
    timeline_event_model.objects.create(
        incident=incident,
        event_type="runbook_generated",
        title="Runbook generated by AI",
        detail=title,
        payload={"runbook_id": runbook.id, "requested_by": str(request_user)},
    )
    return {"runbook_id": runbook.id, "title": title, "content": text}


def explain_anomaly_payload(
    *,
    alert_name: str,
    target_host: str,
    labels: Dict[str, Any],
    summary: str,
    incident,
    llm_query: Callable[[str], tuple],
    timeline_event_model,
) -> Dict[str, str]:
    blast_radius = (incident.blast_radius if incident else []) or []
    prompt = (
        "You are an AIOps observability expert. Explain in plain English why this alert fired.\n"
        "Your explanation must be structured under these exact headings (no markdown, just clear prose):\n"
        "WHAT IT MEASURES: What the alert monitors and what it means for the business.\n"
        "BASELINE vs OBSERVED: What the normal baseline looks like and the scale of the current deviation.\n"
        "CORRELATED EVIDENCE: What other signals, services, or recent changes support this diagnosis.\n"
        "TRIAGE RECOMMENDATION: A single actionable sentence for the on-call engineer.\n\n"
        f"Alert name: {alert_name}\n"
        f"Target host: {target_host}\n"
        f"Labels: {json.dumps(labels)}\n"
        f"AI initial diagnosis: {summary}\n"
        f"Blast radius (affected services): {json.dumps(blast_radius)}\n"
    )
    ok, _, text = llm_query(prompt)
    if not ok:
        raise RuntimeError(text)

    if incident:
        timeline_event_model.objects.create(
            incident=incident,
            event_type="anomaly_explained",
            title=f"Anomaly explanation: {alert_name}",
            detail=text[:500],
            payload={"alert_name": alert_name, "explanation": text},
        )
    return {"alert_name": alert_name, "explanation": text}


def analyze_change_risk_payload(
    *,
    service: str,
    change_description: str,
    planned_at: str,
    change_type: str,
    blast_radius: List[str],
    depends_on: List[str],
    recent_incidents: List[Dict[str, Any]],
    llm_query: Callable[[str], tuple],
) -> Dict[str, Any]:
    prompt = (
        "You are a senior SRE / change advisory board advisor. Analyse the proposed change and return a JSON object ONLY "
        "with these exact keys (no extra text, no markdown fences):\n"
        "{\n"
        '  "risk_score": <integer 1-100>,\n'
        '  "risk_level": "low|medium|high|critical",\n'
        '  "affected_services": ["service1", ...],\n'
        '  "recommended_window": "<day and UTC/IST time, e.g. Saturday 02:00-04:00 IST>",\n'
        '  "rollback_steps": ["step1", ...],\n'
        '  "risk_factors": ["factor1", ...],\n'
        '  "mitigations": ["mitigation1", ...]\n'
        "}\n\n"
        f"Service: {service or 'not specified'}\n"
        f"Change type: {change_type}\n"
        f"Description: {change_description}\n"
        f"Planned at: {planned_at or 'not specified'}\n"
        f"Direct blast radius: {json.dumps(blast_radius)}\n"
        f"Depends on: {json.dumps(depends_on)}\n"
        f"Recent incidents ({len(recent_incidents)}): {json.dumps(recent_incidents)}\n"
    )
    ok, _, text = llm_query(prompt)
    if not ok:
        raise RuntimeError(text)

    try:
        start = text.find("{")
        end = text.rfind("}") + 1
        analysis = json.loads(text[start:end]) if start != -1 else {"raw": text}
    except Exception:
        analysis = {"raw": text}

    return {
        "service": service,
        "change_description": change_description,
        "planned_at": planned_at,
        "change_type": change_type,
        "analysis": analysis,
        "blast_radius": blast_radius,
        "depends_on": depends_on,
    }


def generate_timeline_narrative_payload(
    incident,
    *,
    llm_query: Callable[[str], tuple],
    timeline_event_model,
) -> Dict[str, str]:
    events = []
    for ev in incident.timeline.all().values("event_type", "title", "detail", "created_at"):
        events.append({
            "event_type": ev["event_type"],
            "title": ev["title"],
            "detail": ev["detail"],
            "created_at": ev["created_at"].isoformat(),
        })

    prompt = (
        "You are writing a post-incident review (PIR). Given the timeline events below, "
        "produce a clear chronological narrative of what happened: when it started, how it was detected, "
        "what was investigated, how it was resolved, and any key learnings.\n"
        "Format: A short intro paragraph followed by bullet points for each key event with its timestamp.\n"
        "Keep it factual, past tense, and suitable for sharing with stakeholders.\n\n"
        f"Incident: {incident.title}\n"
        f"Severity: {incident.severity} | Priority: {incident.priority}\n"
        f"Service: {incident.primary_service}\n"
        f"Opened: {incident.opened_at.isoformat()}\n"
        f"Resolved: {incident.resolved_at.isoformat() if incident.resolved_at else 'Still open'}\n\n"
        f"EVENTS ({len(events)}):\n"
        + json.dumps(events, indent=2)[:6000]
    )
    ok, _, text = llm_query(prompt)
    if not ok:
        raise RuntimeError(text)

    timeline_event_model.objects.create(
        incident=incident,
        event_type="pir_generated",
        title="Post-incident narrative generated",
        detail=text[:500],
        payload={"narrative": text},
    )
    return {"incident_key": str(incident.incident_key), "narrative": text}
