import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


User = get_user_model()


class GenAIChatHistory(models.Model):
    """
    Stores a record of each question asked, the raw SQL query generated by the
    Text-to-SQL model, and the final, human-readable answer.
    This also acts as a cache to avoid re-computing answers for repeated questions.
    """
    question = models.TextField(unique=True)
    generated_sql = models.TextField()
    answer = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Q: {self.question[:50]}... -> SQL: {self.generated_sql[:80]}..."


class ChatSession(models.Model):
    session_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="aiops_chat_sessions")
    title = models.CharField(max_length=255, blank=True, default="")
    context_json = models.JSONField(default=dict, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_activity_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"ChatSession<{self.session_id}>"


class ChatMessage(models.Model):
    ROLE_CHOICES = (
        ("user", "User"),
        ("assistant", "Assistant"),
        ("system", "System"),
    )

    session = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name="messages")
    role = models.CharField(max_length=16, choices=ROLE_CHOICES)
    content = models.TextField()
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.session.session_id}:{self.role}:{self.created_at.isoformat()}"


class Incident(models.Model):
    STATUS_CHOICES = (
        ("open", "Open"),
        ("investigating", "Investigating"),
        ("resolved", "Resolved"),
    )

    incident_key = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    application = models.CharField(max_length=120, blank=True, default="")
    title = models.CharField(max_length=255)
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default="open")
    severity = models.CharField(max_length=32, blank=True, default="warning")
    primary_service = models.CharField(max_length=120, blank=True, default="")
    target_host = models.CharField(max_length=255, blank=True, default="")
    summary = models.TextField(blank=True, default="")
    reasoning = models.TextField(blank=True, default="")
    blast_radius = models.JSONField(default=list, blank=True)
    dependency_graph = models.JSONField(default=dict, blank=True)
    labels = models.JSONField(default=dict, blank=True)
    annotations = models.JSONField(default=dict, blank=True)
    opened_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"{self.application or 'unknown'}:{self.title}"


class IncidentAlert(models.Model):
    incident = models.ForeignKey(Incident, on_delete=models.CASCADE, related_name="alerts")
    alert_name = models.CharField(max_length=255)
    alert_fingerprint = models.CharField(max_length=255, blank=True, default="")
    status = models.CharField(max_length=32, default="firing")
    target_host = models.CharField(max_length=255, blank=True, default="")
    service_name = models.CharField(max_length=120, blank=True, default="")
    labels = models.JSONField(default=dict, blank=True)
    annotations = models.JSONField(default=dict, blank=True)
    raw_payload = models.JSONField(default=dict, blank=True)
    first_seen_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-last_seen_at"]

    def __str__(self):
        return f"{self.alert_name} -> {self.incident.incident_key}"


class IncidentTimelineEvent(models.Model):
    incident = models.ForeignKey(Incident, on_delete=models.CASCADE, related_name="timeline")
    event_type = models.CharField(max_length=64)
    title = models.CharField(max_length=255)
    detail = models.TextField(blank=True, default="")
    payload = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.incident.incident_key}:{self.event_type}"


class PredictionSnapshot(models.Model):
    application = models.CharField(max_length=120)
    service = models.CharField(max_length=120)
    captured_at = models.DateTimeField(auto_now_add=True)
    metrics = models.JSONField(default=dict)
    features = models.JSONField(default=dict)
    incident_next_15m = models.BooleanField(default=False)

    class Meta:
        ordering = ["-captured_at"]

    def __str__(self):
        return f"{self.application}/{self.service} @ {self.captured_at.isoformat()}"


class ServicePrediction(models.Model):
    application = models.CharField(max_length=120)
    service = models.CharField(max_length=120)
    status = models.CharField(max_length=32, default="healthy")
    risk_score = models.FloatField(default=0.0)
    incident_probability = models.FloatField(default=0.0)
    predicted_window_minutes = models.PositiveIntegerField(default=15)
    model_version = models.CharField(max_length=120, default="heuristic-v1")
    features = models.JSONField(default=dict)
    blast_radius = models.JSONField(default=list)
    explanation = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.application}/{self.service} risk={self.risk_score:.2f}"


class TelemetryProfile(models.Model):
    slug = models.SlugField(max_length=64, unique=True)
    name = models.CharField(max_length=120)
    summary = models.TextField(blank=True, default="")
    default_for_target = models.CharField(max_length=32, default="linux")
    components = models.JSONField(default=list, blank=True)
    capabilities = models.JSONField(default=list, blank=True)
    config_json = models.JSONField(default=dict, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Target(models.Model):
    STATUS_CHOICES = (
        ("pending", "Pending"),
        ("connected", "Connected"),
        ("warning", "Warning"),
        ("degraded", "Degraded"),
        ("disconnected", "Disconnected"),
    )

    target_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    name = models.CharField(max_length=160)
    target_type = models.CharField(max_length=32, default="linux")
    environment = models.CharField(max_length=64, blank=True, default="production")
    hostname = models.CharField(max_length=255, blank=True, default="")
    ip_address = models.CharField(max_length=64, blank=True, default="")
    os_name = models.CharField(max_length=120, blank=True, default="")
    os_version = models.CharField(max_length=120, blank=True, default="")
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default="pending")
    profile = models.ForeignKey(TelemetryProfile, null=True, blank=True, on_delete=models.SET_NULL, related_name="targets")
    collector_status = models.CharField(max_length=32, default="pending")
    metadata_json = models.JSONField(default=dict, blank=True)
    enrolled_at = models.DateTimeField(auto_now_add=True)
    last_heartbeat_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return self.name


class EnrollmentToken(models.Model):
    token = models.CharField(max_length=96, unique=True, db_index=True)
    target_type = models.CharField(max_length=32, default="linux")
    target_name = models.CharField(max_length=160, blank=True, default="")
    profile = models.ForeignKey(TelemetryProfile, null=True, blank=True, on_delete=models.SET_NULL, related_name="enrollment_tokens")
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="fleet_enrollment_tokens")
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    revoked = models.BooleanField(default=False)
    metadata_json = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.target_type}:{self.token[:12]}"

    @property
    def is_valid(self) -> bool:
        return (not self.revoked) and self.expires_at > timezone.now()


class TargetComponent(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE, related_name="components")
    name = models.CharField(max_length=120)
    version = models.CharField(max_length=64, blank=True, default="")
    status = models.CharField(max_length=32, default="pending")
    metadata_json = models.JSONField(default=dict, blank=True)
    last_seen_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["name"]
        unique_together = ("target", "name")

    def __str__(self):
        return f"{self.target.name}:{self.name}"


class TargetHeartbeat(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE, related_name="heartbeats")
    payload = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.target.name}:{self.created_at.isoformat()}"


class DiscoveredService(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE, related_name="discovered_services")
    service_name = models.CharField(max_length=160)
    process_name = models.CharField(max_length=160, blank=True, default="")
    port = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=32, default="observed")
    metadata_json = models.JSONField(default=dict, blank=True)
    first_seen_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["service_name"]
        unique_together = ("target", "service_name", "port")

    def __str__(self):
        return f"{self.target.name}:{self.service_name}"


class TargetOnboardingRequest(models.Model):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("validated", "Validated"),
        ("installing", "Installing"),
        ("installed", "Installed"),
        ("failed", "Failed"),
    )

    onboarding_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    target_type = models.CharField(max_length=32, default="linux")
    name = models.CharField(max_length=160)
    hostname = models.CharField(max_length=255)
    ssh_user = models.CharField(max_length=120, default="ec2-user")
    ssh_port = models.PositiveIntegerField(default=22)
    profile = models.ForeignKey(TelemetryProfile, null=True, blank=True, on_delete=models.SET_NULL, related_name="onboarding_requests")
    pem_file = models.FileField(upload_to="fleet/pem/")
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default="draft")
    connectivity_status = models.CharField(max_length=32, default="untested")
    connectivity_message = models.TextField(blank=True, default="")
    last_connectivity_check_at = models.DateTimeField(null=True, blank=True)
    last_install_at = models.DateTimeField(null=True, blank=True)
    install_message = models.TextField(blank=True, default="")
    target = models.ForeignKey(Target, null=True, blank=True, on_delete=models.SET_NULL, related_name="onboarding_requests")
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="fleet_onboarding_requests")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"{self.name}:{self.hostname}"
