import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


User = get_user_model()


class GenAIChatHistory(models.Model):
    """
    Stores a record of each question asked, the raw SQL query generated by the
    Text-to-SQL model, and the final, human-readable answer.
    This also acts as a cache to avoid re-computing answers for repeated questions.
    """
    question = models.TextField(unique=True)
    generated_sql = models.TextField()
    answer = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Q: {self.question[:50]}... -> SQL: {self.generated_sql[:80]}..."


class ChatSession(models.Model):
    session_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="aiops_chat_sessions")
    title = models.CharField(max_length=255, blank=True, default="")
    context_json = models.JSONField(default=dict, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_activity_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"ChatSession<{self.session_id}>"


class ChatMessage(models.Model):
    ROLE_CHOICES = (
        ("user", "User"),
        ("assistant", "Assistant"),
        ("system", "System"),
    )

    session = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name="messages")
    role = models.CharField(max_length=16, choices=ROLE_CHOICES)
    content = models.TextField()
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.session.session_id}:{self.role}:{self.created_at.isoformat()}"


class InvestigationRun(models.Model):
    STATUS_CHOICES = (
        ("running", "Running"),
        ("completed", "Completed"),
        ("failed", "Failed"),
    )

    run_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    session = models.ForeignKey("ChatSession", null=True, blank=True, on_delete=models.SET_NULL, related_name="investigation_runs")
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="aiops_investigation_runs")
    incident = models.ForeignKey("Incident", null=True, blank=True, on_delete=models.SET_NULL, related_name="investigation_runs")
    route = models.CharField(max_length=32, default="investigation")
    question = models.TextField()
    application = models.CharField(max_length=120, blank=True, default="")
    service = models.CharField(max_length=120, blank=True, default="")
    target_host = models.CharField(max_length=255, blank=True, default="")
    scope_json = models.JSONField(default=dict, blank=True)
    evidence_summary = models.JSONField(default=dict, blank=True)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default="running")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"InvestigationRun<{self.run_id}>"


class ToolInvocation(models.Model):
    STATUS_CHOICES = (
        ("success", "Success"),
        ("error", "Error"),
    )

    invocation_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    investigation_run = models.ForeignKey("InvestigationRun", null=True, blank=True, on_delete=models.SET_NULL, related_name="tool_invocations")
    session = models.ForeignKey("ChatSession", null=True, blank=True, on_delete=models.SET_NULL, related_name="tool_invocations")
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="aiops_tool_invocations")
    incident = models.ForeignKey("Incident", null=True, blank=True, on_delete=models.SET_NULL, related_name="tool_invocations")
    server_name = models.CharField(max_length=64)
    tool_name = models.CharField(max_length=128)
    request_json = models.JSONField(default=dict, blank=True)
    response_json = models.JSONField(default=dict, blank=True)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default="success")
    latency_ms = models.PositiveIntegerField(default=0)
    error_detail = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.server_name}:{self.tool_name}:{self.invocation_id}"


PRIORITY_CHOICES = (
    ("P1", "P1 - Critical"),
    ("P2", "P2 - High"),
    ("P3", "P3 - Medium"),
    ("P4", "P4 - Low"),
)

# Default SLA windows (minutes) used when seeding SLAPolicy
SLA_DEFAULTS = {
    "P1": (15, 60),
    "P2": (30, 240),
    "P3": (120, 480),
    "P4": (480, 1440),
}


class SLAPolicy(models.Model):
    """Configurable SLA matrix per priority tier."""
    priority = models.CharField(max_length=4, choices=PRIORITY_CHOICES, unique=True)
    response_minutes = models.PositiveIntegerField(default=60)
    resolution_minutes = models.PositiveIntegerField(default=240)
    escalation_contacts = models.JSONField(default=list, blank=True)

    class Meta:
        ordering = ["priority"]

    def __str__(self):
        return f"SLA-{self.priority} resp={self.response_minutes}m res={self.resolution_minutes}m"


class Incident(models.Model):
    STATUS_CHOICES = (
        ("open", "Open"),
        ("investigating", "Investigating"),
        ("resolved", "Resolved"),
    )

    incident_key = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    application = models.CharField(max_length=120, blank=True, default="")
    title = models.CharField(max_length=255)
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default="open")
    severity = models.CharField(max_length=32, blank=True, default="warning")
    priority = models.CharField(max_length=4, choices=PRIORITY_CHOICES, default="P3")
    primary_service = models.CharField(max_length=120, blank=True, default="")
    target_host = models.CharField(max_length=255, blank=True, default="")
    summary = models.TextField(blank=True, default="")
    reasoning = models.TextField(blank=True, default="")
    blast_radius = models.JSONField(default=list, blank=True)
    dependency_graph = models.JSONField(default=dict, blank=True)
    labels = models.JSONField(default=dict, blank=True)
    annotations = models.JSONField(default=dict, blank=True)
    opened_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    # SLA tracking
    sla_response_due_at = models.DateTimeField(null=True, blank=True)
    sla_resolution_due_at = models.DateTimeField(null=True, blank=True)
    sla_response_acknowledged_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"{self.application or 'unknown'}:{self.title}"


class IncidentAlert(models.Model):
    incident = models.ForeignKey(Incident, on_delete=models.CASCADE, related_name="alerts")
    alert_name = models.CharField(max_length=255)
    alert_fingerprint = models.CharField(max_length=255, blank=True, default="")
    status = models.CharField(max_length=32, default="firing")
    target_host = models.CharField(max_length=255, blank=True, default="")
    service_name = models.CharField(max_length=120, blank=True, default="")
    labels = models.JSONField(default=dict, blank=True)
    annotations = models.JSONField(default=dict, blank=True)
    raw_payload = models.JSONField(default=dict, blank=True)
    first_seen_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-last_seen_at"]

    def __str__(self):
        return f"{self.alert_name} -> {self.incident.incident_key}"


class IncidentTimelineEvent(models.Model):
    incident = models.ForeignKey(Incident, on_delete=models.CASCADE, related_name="timeline")
    event_type = models.CharField(max_length=64)
    title = models.CharField(max_length=255)
    detail = models.TextField(blank=True, default="")
    payload = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.incident.incident_key}:{self.event_type}"


class PredictionSnapshot(models.Model):
    application = models.CharField(max_length=120)
    service = models.CharField(max_length=120)
    captured_at = models.DateTimeField(auto_now_add=True)
    metrics = models.JSONField(default=dict)
    features = models.JSONField(default=dict)
    incident_next_15m = models.BooleanField(default=False)

    class Meta:
        ordering = ["-captured_at"]

    def __str__(self):
        return f"{self.application}/{self.service} @ {self.captured_at.isoformat()}"


class ServicePrediction(models.Model):
    application = models.CharField(max_length=120)
    service = models.CharField(max_length=120)
    status = models.CharField(max_length=32, default="healthy")
    risk_score = models.FloatField(default=0.0)
    incident_probability = models.FloatField(default=0.0)
    predicted_window_minutes = models.PositiveIntegerField(default=15)
    model_version = models.CharField(max_length=120, default="heuristic-v1")
    features = models.JSONField(default=dict)
    blast_radius = models.JSONField(default=list)
    explanation = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.application}/{self.service} risk={self.risk_score:.2f}"


class TelemetryProfile(models.Model):
    slug = models.SlugField(max_length=64, unique=True)
    name = models.CharField(max_length=120)
    summary = models.TextField(blank=True, default="")
    default_for_target = models.CharField(max_length=32, default="linux")
    components = models.JSONField(default=list, blank=True)
    capabilities = models.JSONField(default=list, blank=True)
    config_json = models.JSONField(default=dict, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Target(models.Model):
    STATUS_CHOICES = (
        ("pending", "Pending"),
        ("connected", "Connected"),
        ("warning", "Warning"),
        ("degraded", "Degraded"),
        ("disconnected", "Disconnected"),
    )

    target_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    name = models.CharField(max_length=160)
    target_type = models.CharField(max_length=32, default="linux")
    environment = models.CharField(max_length=64, blank=True, default="production")
    hostname = models.CharField(max_length=255, blank=True, default="")
    ip_address = models.CharField(max_length=64, blank=True, default="")
    os_name = models.CharField(max_length=120, blank=True, default="")
    os_version = models.CharField(max_length=120, blank=True, default="")
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default="pending")
    profile = models.ForeignKey(TelemetryProfile, null=True, blank=True, on_delete=models.SET_NULL, related_name="targets")
    collector_status = models.CharField(max_length=32, default="pending")
    metadata_json = models.JSONField(default=dict, blank=True)
    enrolled_at = models.DateTimeField(auto_now_add=True)
    last_heartbeat_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return self.name


class EnrollmentToken(models.Model):
    token = models.CharField(max_length=96, unique=True, db_index=True)
    target_type = models.CharField(max_length=32, default="linux")
    target_name = models.CharField(max_length=160, blank=True, default="")
    profile = models.ForeignKey(TelemetryProfile, null=True, blank=True, on_delete=models.SET_NULL, related_name="enrollment_tokens")
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="fleet_enrollment_tokens")
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    revoked = models.BooleanField(default=False)
    metadata_json = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.target_type}:{self.token[:12]}"

    @property
    def is_valid(self) -> bool:
        return (not self.revoked) and self.expires_at > timezone.now()


class TargetComponent(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE, related_name="components")
    name = models.CharField(max_length=120)
    version = models.CharField(max_length=64, blank=True, default="")
    status = models.CharField(max_length=32, default="pending")
    metadata_json = models.JSONField(default=dict, blank=True)
    last_seen_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["name"]
        unique_together = ("target", "name")

    def __str__(self):
        return f"{self.target.name}:{self.name}"


class TargetHeartbeat(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE, related_name="heartbeats")
    payload = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.target.name}:{self.created_at.isoformat()}"


class DiscoveredService(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE, related_name="discovered_services")
    service_name = models.CharField(max_length=160)
    process_name = models.CharField(max_length=160, blank=True, default="")
    port = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=32, default="observed")
    metadata_json = models.JSONField(default=dict, blank=True)
    first_seen_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["service_name"]
        unique_together = ("target", "service_name", "port")

    def __str__(self):
        return f"{self.target.name}:{self.service_name}"


class TargetOnboardingRequest(models.Model):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("validated", "Validated"),
        ("installing", "Installing"),
        ("installed", "Installed"),
        ("failed", "Failed"),
    )

    onboarding_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    target_type = models.CharField(max_length=32, default="linux")
    name = models.CharField(max_length=160)
    hostname = models.CharField(max_length=255)
    ssh_user = models.CharField(max_length=120, default="ec2-user")
    ssh_port = models.PositiveIntegerField(default=22)
    profile = models.ForeignKey(TelemetryProfile, null=True, blank=True, on_delete=models.SET_NULL, related_name="onboarding_requests")
    pem_file = models.FileField(upload_to="fleet/pem/")
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default="draft")
    connectivity_status = models.CharField(max_length=32, default="untested")
    connectivity_message = models.TextField(blank=True, default="")
    last_connectivity_check_at = models.DateTimeField(null=True, blank=True)
    last_install_at = models.DateTimeField(null=True, blank=True)
    install_message = models.TextField(blank=True, default="")
    target = models.ForeignKey(Target, null=True, blank=True, on_delete=models.SET_NULL, related_name="onboarding_requests")
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="fleet_onboarding_requests")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"{self.name}:{self.hostname}"


class Runbook(models.Model):
    """AI-generated runbook produced from incident RCA and remediation steps."""
    incident = models.ForeignKey(
        Incident, on_delete=models.CASCADE, related_name="runbooks", null=True, blank=True
    )
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title


class AgentBehaviorVersion(models.Model):
    behavior_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    name = models.CharField(max_length=120, default="default")
    prompt_version = models.CharField(max_length=120, default="prompt-v1")
    policy_version = models.CharField(max_length=120, default="policy-v1")
    model_version = models.CharField(max_length=120, default="model-v1")
    evidence_rules_version = models.CharField(max_length=120, default="evidence-v1")
    ranking_version = models.CharField(max_length=120, default="ranking-v1")
    metadata_json = models.JSONField(default=dict, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self):
        return f"{self.name}:{self.behavior_id}"


class ExecutionIntent(models.Model):
    STATUS_CHOICES = (
        ("planned", "Planned"),
        ("approval_required", "Approval Required"),
        ("approved", "Approved"),
        ("dry_run", "Dry Run"),
        ("blocked", "Blocked"),
        ("executing", "Executing"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("expired", "Expired"),
    )

    intent_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    session = models.ForeignKey(ChatSession, null=True, blank=True, on_delete=models.SET_NULL, related_name="execution_intents")
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="aiops_execution_intents")
    incident = models.ForeignKey(Incident, null=True, blank=True, on_delete=models.SET_NULL, related_name="execution_intents")
    behavior_version = models.ForeignKey(AgentBehaviorVersion, null=True, blank=True, on_delete=models.SET_NULL, related_name="execution_intents")
    execution_type = models.CharField(max_length=32, default="diagnostic")
    action_type = models.CharField(max_length=64, blank=True, default="")
    service = models.CharField(max_length=120, blank=True, default="")
    environment = models.CharField(max_length=64, blank=True, default="")
    target_host = models.CharField(max_length=255, blank=True, default="")
    command = models.TextField(blank=True, default="")
    action_json = models.JSONField(default=dict, blank=True)
    action_signature = models.CharField(max_length=128, blank=True, default="", db_index=True)
    request_signature = models.CharField(max_length=128, blank=True, default="")
    idempotency_key = models.CharField(max_length=128, blank=True, default="", db_index=True)
    requires_approval = models.BooleanField(default=False)
    approval_token_hash = models.CharField(max_length=128, blank=True, default="")
    approval_expires_at = models.DateTimeField(null=True, blank=True)
    approved_at = models.DateTimeField(null=True, blank=True)
    approved_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="approved_execution_intents")
    dry_run = models.BooleanField(default=False)
    rollback_json = models.JSONField(default=dict, blank=True)
    policy_decision_json = models.JSONField(default=dict, blank=True)
    ranking_json = models.JSONField(default=dict, blank=True)
    verification_json = models.JSONField(default=dict, blank=True)
    response_json = models.JSONField(default=dict, blank=True)
    context_fingerprint = models.CharField(max_length=128, blank=True, default="", db_index=True)
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default="planned")
    executed_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.intent_id}:{self.execution_type}:{self.status}"


class RemediationOutcome(models.Model):
    outcome_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    execution_intent = models.ForeignKey(ExecutionIntent, on_delete=models.CASCADE, related_name="outcomes")
    incident = models.ForeignKey(Incident, null=True, blank=True, on_delete=models.SET_NULL, related_name="remediation_outcomes")
    action_type = models.CharField(max_length=64, blank=True, default="")
    service = models.CharField(max_length=120, blank=True, default="")
    environment = models.CharField(max_length=64, blank=True, default="")
    context_fingerprint = models.CharField(max_length=128, blank=True, default="", db_index=True)
    action_signature = models.CharField(max_length=128, blank=True, default="", db_index=True)
    success = models.BooleanField(default=False)
    verification_status = models.CharField(max_length=64, blank=True, default="")
    time_to_recovery_seconds = models.PositiveIntegerField(null=True, blank=True)
    recurrence_within_minutes = models.PositiveIntegerField(null=True, blank=True)
    blast_radius_risk = models.FloatField(null=True, blank=True)
    operator_override = models.BooleanField(default=False)
    metadata_json = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.action_type}:{self.service}:{self.success}"


class ReplayScenario(models.Model):
    scenario_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    incident = models.ForeignKey(Incident, null=True, blank=True, on_delete=models.SET_NULL, related_name="replay_scenarios")
    session = models.ForeignKey(ChatSession, null=True, blank=True, on_delete=models.SET_NULL, related_name="replay_scenarios")
    source = models.CharField(max_length=32, default="execution")
    title = models.CharField(max_length=255, blank=True, default="")
    alert_payload_json = models.JSONField(default=dict, blank=True)
    metrics_snapshot_json = models.JSONField(default=dict, blank=True)
    logs_snapshot_json = models.JSONField(default=dict, blank=True)
    traces_snapshot_json = models.JSONField(default=dict, blank=True)
    dependency_context_json = models.JSONField(default=dict, blank=True)
    prior_incident_memory_json = models.JSONField(default=dict, blank=True)
    chosen_action_json = models.JSONField(default=dict, blank=True)
    outcome_json = models.JSONField(default=dict, blank=True)
    behavior_version_json = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.source}:{self.scenario_id}"


class ReplayEvaluation(models.Model):
    STATUS_CHOICES = (
        ("completed", "Completed"),
        ("failed", "Failed"),
    )

    evaluation_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    scenario = models.ForeignKey(ReplayScenario, on_delete=models.CASCADE, related_name="evaluations")
    execution_intent = models.ForeignKey(ExecutionIntent, null=True, blank=True, on_delete=models.SET_NULL, related_name="replay_evaluations")
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default="completed")
    scores_json = models.JSONField(default=dict, blank=True)
    summary_json = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.evaluation_id}:{self.status}"


class OperatorFeedback(models.Model):
    FEEDBACK_CHOICES = (
        ("accepted", "Accepted"),
        ("rejected", "Rejected"),
        ("edited", "Edited"),
        ("manual_fix", "Manual Fix Applied"),
    )

    QUALITY_CHOICES = (
        ("excellent", "Excellent"),
        ("good", "Good"),
        ("partial", "Partial"),
        ("poor", "Poor"),
        ("unknown", "Unknown"),
    )

    feedback_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    execution_intent = models.ForeignKey(ExecutionIntent, null=True, blank=True, on_delete=models.SET_NULL, related_name="operator_feedback")
    incident = models.ForeignKey(Incident, null=True, blank=True, on_delete=models.SET_NULL, related_name="operator_feedback")
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="aiops_operator_feedback")
    feedback_type = models.CharField(max_length=32, choices=FEEDBACK_CHOICES)
    outcome_quality = models.CharField(max_length=32, choices=QUALITY_CHOICES, default="unknown")
    service = models.CharField(max_length=120, blank=True, default="")
    environment = models.CharField(max_length=64, blank=True, default="")
    action_type = models.CharField(max_length=64, blank=True, default="")
    context_fingerprint = models.CharField(max_length=128, blank=True, default="", db_index=True)
    original_action_json = models.JSONField(default=dict, blank=True)
    submitted_action_json = models.JSONField(default=dict, blank=True)
    notes = models.TextField(blank=True, default="")
    metadata_json = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.feedback_type}:{self.service}:{self.created_at.isoformat()}"


class RepositoryIndex(models.Model):
    INDEX_STATUS_CHOICES = (
        ("pending", "Pending"),
        ("indexed", "Indexed"),
        ("failed", "Failed"),
    )

    repository_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    name = models.CharField(max_length=255)
    local_path = models.CharField(max_length=1024, unique=True)
    default_branch = models.CharField(max_length=255, blank=True, default="main")
    provider = models.CharField(max_length=64, blank=True, default="local")
    repo_identifier = models.CharField(max_length=255, blank=True, default="")
    is_active = models.BooleanField(default=True)
    index_status = models.CharField(max_length=16, choices=INDEX_STATUS_CHOICES, default="pending")
    last_indexed_at = models.DateTimeField(null=True, blank=True)
    last_index_error = models.TextField(blank=True, default="")
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}:{self.local_path}"


class ServiceRepositoryBinding(models.Model):
    binding_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    service_name = models.CharField(max_length=120, db_index=True)
    application_name = models.CharField(max_length=120, blank=True, default="", db_index=True)
    repository_index = models.ForeignKey(RepositoryIndex, on_delete=models.CASCADE, related_name="service_bindings")
    team_name = models.CharField(max_length=255, blank=True, default="")
    ownership_confidence = models.FloatField(default=0.5)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["service_name", "application_name"]
        unique_together = ("service_name", "application_name", "repository_index")

    def __str__(self):
        return f"{self.service_name}:{self.repository_index.name}"


class RouteBinding(models.Model):
    binding_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    service_name = models.CharField(max_length=120, blank=True, default="", db_index=True)
    repository_index = models.ForeignKey(RepositoryIndex, on_delete=models.CASCADE, related_name="route_bindings")
    http_method = models.CharField(max_length=16, blank=True, default="ANY")
    route_pattern = models.CharField(max_length=512, db_index=True)
    handler_name = models.CharField(max_length=255, blank=True, default="")
    handler_file_path = models.CharField(max_length=1024, blank=True, default="")
    line_start = models.PositiveIntegerField(null=True, blank=True)
    line_end = models.PositiveIntegerField(null=True, blank=True)
    confidence = models.FloatField(default=0.5)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["route_pattern", "http_method"]
        unique_together = ("repository_index", "http_method", "route_pattern", "handler_name", "handler_file_path")

    def __str__(self):
        return f"{self.http_method}:{self.route_pattern}"


class SpanBinding(models.Model):
    binding_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    service_name = models.CharField(max_length=120, blank=True, default="", db_index=True)
    repository_index = models.ForeignKey(RepositoryIndex, on_delete=models.CASCADE, related_name="span_bindings")
    span_name = models.CharField(max_length=255, db_index=True)
    symbol_name = models.CharField(max_length=255, blank=True, default="")
    symbol_file_path = models.CharField(max_length=1024, blank=True, default="")
    line_start = models.PositiveIntegerField(null=True, blank=True)
    line_end = models.PositiveIntegerField(null=True, blank=True)
    confidence = models.FloatField(default=0.5)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["span_name"]
        unique_together = ("repository_index", "span_name", "symbol_name", "symbol_file_path")

    def __str__(self):
        return f"{self.span_name}:{self.symbol_name}"


class DeploymentBinding(models.Model):
    binding_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    service_name = models.CharField(max_length=120, db_index=True)
    environment = models.CharField(max_length=64, blank=True, default="", db_index=True)
    version = models.CharField(max_length=255, db_index=True)
    repository_index = models.ForeignKey(RepositoryIndex, on_delete=models.CASCADE, related_name="deployment_bindings")
    commit_sha = models.CharField(max_length=64, blank=True, default="", db_index=True)
    deployed_at = models.DateTimeField(null=True, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-deployed_at", "-created_at"]
        unique_together = ("service_name", "environment", "version", "repository_index")

    def __str__(self):
        return f"{self.service_name}:{self.version}"


class CodeChangeRecord(models.Model):
    change_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    repository_index = models.ForeignKey(RepositoryIndex, on_delete=models.CASCADE, related_name="change_records")
    commit_sha = models.CharField(max_length=64, db_index=True)
    author = models.CharField(max_length=255, blank=True, default="")
    title = models.CharField(max_length=512, blank=True, default="")
    changed_files = models.JSONField(default=list, blank=True)
    committed_at = models.DateTimeField(null=True, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-committed_at", "-created_at"]
        unique_together = ("repository_index", "commit_sha")

    def __str__(self):
        return f"{self.repository_index.name}:{self.commit_sha[:12]}"


class SymbolRelation(models.Model):
    relation_id = models.CharField(max_length=64, unique=True, default=uuid.uuid4, db_index=True)
    repository_index = models.ForeignKey(RepositoryIndex, on_delete=models.CASCADE, related_name="symbol_relations")
    source_symbol = models.CharField(max_length=255, db_index=True)
    source_file_path = models.CharField(max_length=1024, blank=True, default="")
    target_symbol = models.CharField(max_length=255, db_index=True)
    target_file_path = models.CharField(max_length=1024, blank=True, default="")
    relation_type = models.CharField(max_length=64, default="calls")
    confidence = models.FloatField(default=0.5)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["source_symbol", "target_symbol"]
        unique_together = (
            "repository_index",
            "source_symbol",
            "source_file_path",
            "target_symbol",
            "target_file_path",
            "relation_type",
        )

    def __str__(self):
        return f"{self.source_symbol}->{self.target_symbol}"
