apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsmitra.fullname" . }}-secret
  labels:
    {{- include "opsmitra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.application.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
